<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Administrador extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Administrador_model');
    }

    /*
     * Listing of administradores
     */

    function index()
    {
        if ($this->session->userdata("login")) {
            $params['limit'] = RECORDS_PER_PAGE;
            $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

            $config = $this->config->item('pagination');
            $config['base_url'] = site_url('administrador/index?');
            $config['total_rows'] = $this->Administrador_model->get_all_administradores_count();
            $this->pagination->initialize($config);

            $data['administradores'] = $this->Administrador_model->get_all_administradores($params);

            $data['_view'] = 'administrador/index';
            $this->load->view('layouts/main', $data);
        } else {
            $this->load->view('vitrina/login');
        }
    }

    /*
     * Adding a new administrador
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'contrasena' => $this->input->post('contrasena'),
                'nombre' => $this->input->post('nombre'),
                'correo' => $this->input->post('correo'),
                'creado_en' => $this->input->post('creado_en'),
            );

            $administrador_id = $this->Administrador_model->add_administrador($params);
            redirect('administrador/index');
        } else {
            $data['_view'] = 'administrador/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a administrador
     */
    function edit($id)
    {
        // check if the administrador exists before trying to edit it
        $data['administrador'] = $this->Administrador_model->get_administrador($id);

        if (isset($data['administrador']['id'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'contrasena' => $this->input->post('contrasena'),
                    'nombre' => $this->input->post('nombre'),
                    'correo' => $this->input->post('correo'),
                    'creado_en' => $this->input->post('creado_en'),
                );

                $this->Administrador_model->update_administrador($id, $params);
                redirect('administrador/index');
            } else {
                $data['_view'] = 'administrador/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The administrador you are trying to edit does not exist.');
    }

    /*
     * Deleting administrador
     */
    function remove($id)
    {
        $administrador = $this->Administrador_model->get_administrador($id);

        // check if the administrador exists before trying to delete it
        if (isset($administrador['id'])) {
            $this->Administrador_model->delete_administrador($id);
            redirect('administrador/index');
        } else
            show_error('The administrador you are trying to delete does not exist.');
    }
}
