<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Administrador_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get administrador by id
     */
    function get_administrador($id)
    {
        return $this->db->get_where('administradores', array('id' => $id))->row_array();
    }

    /*
     * Get all administradores count
     */
    function get_all_administradores_count()
    {
        $this->db->from('administradores');
        return $this->db->count_all_results();
    }

    /*
     * Get all administradores
     */
    function get_all_administradores($params = array())
    {
        $this->db->order_by('id', 'desc');
        if (isset($params) && !empty($params)) {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('administradores')->result_array();
    }

    /*
     * function to add new administrador
     */
    function add_administrador($params)
    {
        $this->db->insert('administradores', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update administrador
     */
    function update_administrador($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('administradores', $params);
    }

    /*
     * function to delete administrador
     */
    function delete_administrador($id)
    {
        return $this->db->delete('administradores', array('id' => $id));
    }
    public function Login($correo, $contrasena)
    {
        $this->db->where("correo", $correo);
        $this->db->where("contrasena", $contrasena);
        $resultados = $this->db->get("administradores");
        if ($resultados->num_rows() > 0) {
            return $resultados->row();
        } else {
            return false;
        }
    }
}
